
             QSYS/PGM
             QSYS/DCL   VAR(&PROFILE) TYPE(*CHAR) LEN(10)
             QSYS/RTVJOBA CURUSER(&PROFILE)
             QSYS/OVRDBF FILE(LRN400STR) TOFILE(VCF/&PROFILE)
             QSYS/CALL  PGM(VCF/LRN400)
             QSYS/DLTOVR FILE(LRN400STR)
             QSYS/ENDPGM
